spring:
  application:
    #应用名称
    name: bysj
  datasource:
    #数据源连接池
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bysj?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      name: defaultDataSource
      username: root
      password: root
  redis:
    host: localhost #默认为localhost
    password: #默认为空
    timeout: PT30M
  session:
    store-type: redis
    timeout: PT30M
  security:
    user:
      name: user
      password: 111111
# 应用服务 WEB 访问端口
server:
  port: 8888
# MybatisPlus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
secret:
  jwt:
    header: Authorization
    expire: 604800 #七天,秒
    secret: qeglherighqeoghqeoHeqrnh23489hl4
